version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2204:current
    resource_class: large

    steps:
      - run:
          name: Setup packages
          command: |
            sudo DEBIAN_FRONTEND=noninteractive apt-get update -y
            sudo DEBIAN_FRONTEND=noninteractive apt-get install -y repo bc bison build-essential curl ccache coreutils flex g++-multilib gcc-multilib git gnupg \
            gperf libxml2 lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libwxgtk3.0-gtk3-dev imagemagick lunzip lzop schedtool squashfs-tools xsltproc zip \
            zlib1g-dev perl xmlstarlet virtualenv xz-utils rr jq libncurses5 pngcrush lib32ncurses5-dev git-lfs libxml2 openjdk-11-jdk wget lib32readline-dev \
            libssl-dev libxml2-utils android-sdk-libsparse-utils lld zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 \
            lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig ca-certificates bc cpio imagemagick \
            bsdmainutils lz4 aria2 rclone ssh-client libncurses5 libssl-dev rsync schedtool python-is-python3 libarchive-tools python3
            
      - run:
          name: Starting the script
          command: |
            curl -s https://raw.githubusercontent.com/popoASM/builder/main/kernelpopo.sh | bash
          no_output_timeout : 2h
